# Generated by Django 6.0.2 on 2026-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDengueEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('semana', models.PositiveIntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('casos_masculino', models.PositiveIntegerField(default=0)),
                ('casos_feminino', models.PositiveIntegerField(default=0)),
                ('casos_hospitalizados', models.PositiveIntegerField(default=0)),
                ('faixa_0_18', models.PositiveIntegerField(default=0)),
                ('faixa_19_35', models.PositiveIntegerField(default=0)),
                ('faixa_36_50', models.PositiveIntegerField(default=0)),
                ('faixa_51_65', models.PositiveIntegerField(default=0)),
                ('faixa_65_mais', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dados de Dengue por Estado',
                'verbose_name_plural': 'Dados de Dengue por Estado',
                'unique_together': {('ano', 'semana', 'uf')},
            },
        ),
    ]
